In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("tested.csv")

In [3]:
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    str
 4   Sex          418 non-null    str
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    str
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     str
 11  Embarked     418 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 56.1 KB

In [5]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [6]:
df.shape

(418, 12)

In [7]:
df.columns.to_list()

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [8]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
num_cols = df.select_dtypes(include=np.number).columns.to_list()
num_cols

['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

In [11]:
obj_cols = df.select_dtypes(include="str").columns.to_list()
obj_cols

['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']

In [12]:
df[obj_cols].nunique().sort_values(ascending=False)

Name        418
Ticket      363
Cabin        76
Embarked      3
Sex           2
dtype: int64

In [13]:
for col in obj_cols:
    
    uniques = df[col].unique()
    print(f"{col:35s} - unique values: {df[col].nunique():3d} - sample: {uniques[:10]}")

Name                                - unique values: 418 - sample: <ArrowStringArray>
[                            'Kelly, Mr. James',
             'Wilkes, Mrs. James (Ellen Needs)',
                    'Myles, Mr. Thomas Francis',
                             'Wirz, Mr. Albert',
 'Hirvonen, Mrs. Alexander (Helga E Lindqvist)',
                   'Svensson, Mr. Johan Cervin',
                         'Connolly, Miss. Kate',
                 'Caldwell, Mr. Albert Francis',
    'Abrahim, Mrs. Joseph (Sophie Halaut Easu)',
                      'Davies, Mr. John Samuel']
Length: 10, dtype: str
Sex                                 - unique values:   2 - sample: <ArrowStringArray>
['male', 'female']
Length: 2, dtype: str
Ticket                              - unique values: 363 - sample: <ArrowStringArray>
[   '330911',    '363272',    '240276',    '315154',   '3101298',      '7538',
    '330972',    '248738',      '2657', 'A/4 48871']
Length: 10, dtype: str
Cabin                               - unique values:  76 - sample: <ArrowStringArray>
[nan, 'B45', 'E31', 'B57 B59 B63 B66', 'B36', 'A21', 'C78', 'D34', 'D19',
 'A9']
Length: 10, dtype: str
Embarked                            - unique values:   3 - sample: <ArrowStringArray>
['Q', 'S', 'C']
Length: 3, dtype: str

In [14]:
df_clean = df.drop(["PassengerId" , 'Name' , 'Ticket' , 'Cabin'] ,axis=1)

In [15]:
df_clean.head(3)

   Survived  Pclass     Sex   Age  SibSp  Parch    Fare Embarked
0         0       3    male  34.5      0      0  7.8292        Q
1         1       3  female  47.0      1      0  7.0000        S
2         0       2    male  62.0      0      0  9.6875        Q

In [16]:
df_clean["Sex"] = df_clean["Sex"].map({'male':1 , 'female':0}).astype(int)

In [17]:
df_clean.isna().sum()

Survived     0
Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [18]:
print(df_clean[df_clean["Fare"].isna()])

     Survived  Pclass  Sex   Age  SibSp  Parch  Fare Embarked
152         0       3    1  60.5      0      0   NaN        S

In [19]:
print(df_clean.loc[(df_clean["Pclass"] == 3) & (df_clean["Embarked"] == "S"), "Fare"].mean().round(2))

13.91

In [20]:
df_clean["Fare"] = df_clean["Fare"].fillna(13.91)

In [21]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  418 non-null    int64
 1   Pclass    418 non-null    int64
 2   Sex       418 non-null    int64
 3   Age       332 non-null    float64
 4   SibSp     418 non-null    int64
 5   Parch     418 non-null    int64
 6   Fare      418 non-null    float64
 7   Embarked  418 non-null    str
dtypes: float64(2), int64(5), str(1)
memory usage: 26.7 KB

In [22]:
df_clean["Embarked"].value_counts()

Embarked
S    270
C    102
Q     46
Name: count, dtype: int64

In [23]:
df_clean = pd.get_dummies(df_clean , columns=["Embarked"], dtype=int)

In [24]:
df_clean.head(2)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,0,3,1,34.5,0,0,7.8292,0,1,0
1,1,3,0,47.0,1,0,7.0000,0,0,1